export const ACTIONS = {
	"CHANGE_COLOR": "CHANGE_COLOR",
	"COLOR_ADD":"COLOR_ADD",
	"COLOR_REMOVE":"COLOR_REMOVE",
	"COLOR_SET_NAME":"COLOR_SET_NAME",
	"PRESET_ADD":"PRESET_ADD",
	"PREPROCESSOR_SET":"PREPROCESSOR_SET",
	"COLORS_LOAD":"COLORS_LOAD",
	"COLORS_SET":"COLORS_SET"
}

export const DEFAULT_COLOR = '#f5f5f5'
